{% set name = "pyfizi" %}
{% set version = "0.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3c878f4f47370cbb9e6b7719d86c5db58e4057a426e22a3232846948d9505f5

build:
  skip: True  # [win or py<37 or python_impl == "pypy"]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.14.5
    - pandas >=1.2.0
    - pandas-plink
    - python
    - scipy >=1.2.0

test:
  imports:
    - pyfizi
  commands:
    - fizi --help

about:
  home: https://github.com/bogdanlab/fizi
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Impute GWAS summary statistics using reference genotype data
  dev_url: https://github.com/bogdanlab/fizi

extra:
  recipe-maintainers:
    - quattro
