travis:
  secure:
    BINSTAR_TOKEN: GRWCZ1Ow5BA8Yuw+fTKDtkA80gSY8JW7r3mL4aTisYsDsfaWsxMxGebE53O1OxCnHlJdGT1lOYhM6jqDEkjRa7pUX9xK6hfufEz2CZ05Fi+CBcN1CEuV78Rt+eb1SbveGumKHHM4UrbVAXagTjTWyrmQEezRumybPMhucEpDmNMdayPoJQ0t8ThDLLkzrkzqHew5VRqc9BKTy4j+P7Fu3sGUvRPWtJYCzVgSRcCnnp8lComn5kR008aOYlLnS1mvZB8Rgg5Ytr09FThRxGf0gnCPC5xbXvRm7wjn1hPsDX7GeLjK0rw0yskLhSp7f9+tuLrG6oW4L6c7VFHxcldYQn/zrFv8M9Ct6N+2qUo3wWIzHqiTq+Q2MNMwZkN6SYqo7tlehbfOvSTqZk/FF1Tq5atOJdv+cIItzYunLTnWgCMWg8TgyCAU3B4JPB2vyegT2wfBR2c18qmmGQx0MWAlVJIrOg2dQc4rKxpUgfFoIK320d0NBadduEvqgl96ozg8aqVTnfM9B6BYYyhBN4qdwGDcirUSy7sPAIYcHZ5w6HJhfMsLoSAktizsF+ys+S79d3qtCNL2I1OYZulDuDM5VkDGgrSTtdnJaNsVBOs6BvRIFzUnHqcbrmMDcltKpv1vhJwSJ0W40wQb1kFOgQUAFdmqMR92BSXWI5zJd60OfKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
